### ISSUE TITLE
Allow File Based Input of Search Terms

### ISSUE THREAD

**Issue by ChrisTruncer** [Veil-Framework/PowerTools#14]
We've been requested to potentially allow users to provide a file containing the search teams to look for within Invoke-FileFinder.  This would be similar to how hosts can be provided within a hosts file.

**Comment by HarmJ0y** [comment]
Added with https://github.com/Veil-Framework/PowerTools/commit/c6dfe49c981a747e98b377b01771524e40595a4c :)
