### ISSUE TITLE
New function please, Invoke-FileDownloader

### ISSUE THREAD

**Issue by digininja** [Veil-Framework/PowerTools#19]
It would take output from Invoke-FileFinder and download all the files in the list to a local directory.

**Comment by HarmJ0y** [comment]
Try cloning this branch https://github.com/Veil-Framework/PowerTools/tree/ping_speedup

"Invoke-FileFinder -ShareList .\shares.txt | Invoke-FileDownloader" should download all files to .\Downloads\, preserving the recursive directory structure of the source. Let me know if there are any issues.

**Comment by digininja** [comment]
I assume I can just cat an existing file into it rather than having to run
the finder again.

cat file_list | | Invoke-FileDownloader

**Comment by HarmJ0y** [comment]
Pipeline should now accept a straight filepath list or the object output of filefinder. You can also supply -FileList .\files.txt.

Also, the *Threaded versions of meta-functions should be fixed. Unthreaded version (invoke-sharefinder/etc.) now so parallel ping resolution first (and then enumeration in serial) for a speed up, and the Threaded versions try 20 enumerations at once.

**Comment by digininja** [comment]
Great, will give it a go.
