### ISSUE TITLE
Invoke-EnumerateLocalAdmins failed with problem writing to file

### ISSUE THREAD

**Issue by digininja** [Veil-Framework/PowerTools#20]
I tried to back up the file Invoke-EnumerateLocalAdmins was  saving its data to and must have done it just as it tried to write so it failed with the following error:
```
VERBOSE: [*] Enumerating server abc.com (12551 of 16544)
Out-File : The process cannot access the file 'admins.csv' because it is being used by another process.
At line:1 char:117
+ ConvertTo-Csv -NoTypeInformation  | Foreach-Object {$start=$true}{if ($start)
 {$start=$false} else {$_}}  | Out-File <<<<  -FilePath 'admins.csv' -Encoding
'ASCII' -Append
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou
   tFileCommand
```
It would be good if it had a way to try to recover from this, especially as I was at 12551 of 16544 servers scanned.

Is there a way to tell it to start again on the server it was trying when it failed? I have a list of all the servers and I have a list of all that it already scanned.

**Comment by ChrisTruncer** [comment]
I believe you should be able to do that with the built in switches right now.  You should be able to use the parameter "-HostList" and a filename.  It will then connect to only the systems in that file.  So in this case, you should be able to give it the file containing just the systems you haven't enumerated yet.

**Comment by digininja** [comment]
I'll check that out, thanks
