### ISSUE TITLE
missing domain

### ISSUE THREAD

**Issue by digininja** [Veil-Framework/PowerTools#22]
https://github.com/Veil-Framework/PowerTools/blob/master/PowerView/powerview.ps1

In the example on the line 2780:
```
 Invoke-NetGroupUserAdd -UserName john -GroupName "Domain Admins" -Domain 
```

You are missing the domain name

**Comment by HarmJ0y** [comment]
Fixed in the SUH_dev branch, which will be merged to master this week. Thanks!
