### ISSUE TITLE
warning on import

### ISSUE THREAD

**Issue by digininja** [Veil-Framework/PowerTools#27]
I know this doesn't affect operations but reporting it as it looks untidy:

```
VERBOSE: Importing function 'ConvertTo-JSON'.
WARNING: Some imported command names include unapproved verbs which might make
them less discoverable.  Use the Verbose parameter for more detail or type
Get-Verb to see the list of approved verbs.
VERBOSE: The command name 'Escape-JSONString' includes an unapproved verb which
 might make it less discoverable.

**Comment by andyrobbins** [comment]
What command are you running to get this error? I tried replicating this issue with Import-Module -Verbose .\powerview.ps1, but it doesn't throw the error for me:
![image](https://cloud.githubusercontent.com/assets/842644/7990460/2d0d5196-0abf-11e5-8e32-59efbc936319.png)

**Comment by digininja** [comment]
Just the basic module import.
