### ISSUE TITLE
Feature Request: Detailed output

### ISSUE THREAD

**Issue by Viss** [Veil-Framework/PowerTools#31]
While waiting for the userhunter(s) to complete, it would be super handy to have powerview say something like:
X number of machines discovered on X domain.
YY of XX machines examined, ZZ minutes/seconds remaining

Just to get an idea of "should I walk away from this or not". 
On average, this one client we have, running stealthuserhunter takes 2-3 hours.

**Comment by ChrisTruncer** [comment]
If you use the -Verbose flag, it will display the total number of hosts that will be searched for users.  It doesn't say "X of Y Machines" like a status, but you should at least see a total number of systems.
