### ISSUE TITLE
Powerview Get-NetUsers does not exist

### ISSUE THREAD

**Issue by carnal0wnage** [Veil-Framework/PowerTools#4]
PS C:\Users\xxxxxxDesktop\PowerTools\PowerView> Get-NetUsers
Get-NetUsers : The term 'Get-NetUsers' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-NetUsers
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetUsers:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by HarmJ0y** [comment]
The Get-NetUsers cmdlet was rolled into Get-NetUser with flexible filters. If you want just user names, you can do "Get-NetUser | %{$_.samaccountname}" (if you want other fields you can extract those as needed). If you want just one user, do "Get-NetUser NAME". NAME also accepts wildcards if you want to search for a set of users.

**Comment by carnal0wnage** [comment]
thanks. was just pointing it out b/c it was in the documentation

**Comment by HarmJ0y** [comment]
derp, thanks for catching that. should be corrected now.
