### ISSUE TITLE
Invoke-UserHunterThreaded Property 'runspacepool" error

### ISSUE THREAD

**Issue by jlang7** [Veil-Framework/PowerTools#9]
PS C:\temp\data> Invoke-UserHunterThreaded -GroupName {GroupName}  -HostList {HostList} -MaxThreads 10 -Verbose
[*] Running Invoke-UserHunterThreaded with delay of

[*] Querying domain group {GroupName} for target users...
[*] Total number of hosts: {TotalCount}

VERBOSE: [*] Enumerating server {SystemName} (1 of {TotalCount})
Property 'runspacepool' cannot be found on this object; make sure it exists and is settable.
At {PowerViewPath}\powerview.ps1:5215 char:31
+                 $ps[$counter]. <<<< runspacepool = $pool
    + CategoryInfo          : InvalidOperation: (runspacepool:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At {PowerViewPath}\powerview.ps1:5218 char:46
+                 [void]$ps[$counter].AddScript <<<< ($EnumServerBlock).AddParameter('Server', $server).AddParameter('Ping', -not $NoPing).AddParameter('TargetUsers', $TargetUsers).AddParameter('CurrentUser', $CurrentUser).AddParameter('CurrentUserBase', $CurrentUserBase)
    + CategoryInfo          : InvalidOperation: (AddScript:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At {PowerViewPath}\powerview.ps1:5221 char:51
+                 $jobs += $ps[$counter].BeginInvoke <<<< ();
    + CategoryInfo          : InvalidOperation: (BeginInvoke:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by HarmJ0y** [comment]
This should hopefully be corrected with the ping_speedup branch, which should be merged into master soon https://github.com/veil-framework/PowerTools/tree/ping_speedup
